seed: 42

output_path: /home/alshev/Projects/hair_segmentation_test_assignment/outputs
data_path: /home/alshev/Projects/hair_segmentation_test_assignment/datasets/processed/

data:
  train:
    batch_size: 24
    size: [256, 256]
    num_workers: 5
    dataset_name: celeba_hq

  val:
    batch_size: 16
    size: [512, 512]
    num_workers: 5
    dataset_name: celeba_hq