seed: 42
gpu: 0

output_path: <PAST_YOUR_PATH>
data_path: <PAST_YOUR_PATH>

data:
  gray: True
  train:
    batch_size: 16
    size: [256, 256]
    num_workers: 5
    dataset_name: celeba_hq

  val:
    batch_size: 16
    size: [256, 256]
    num_workers: 5
    dataset_name: celeba_hq

model:
  type: UNet
  loss: HairMatting

optimizer:
  name: Adam
  lr: 3e-4

train:
  epochs: 35
